services:
  api:
    build:
      context: ./customer-api
      dockerfile: Dockerfile
    container_name: customer_api
    restart: always
    working_dir: /var/www
    volumes:
      - ./customer-api:/var/www
      - ./customer-api:/var/www/storage/framework
      - ./customer-api:/var/www/storage/framework/sessions
      - ./customer-api:/var/www/storage/framework/views
      - ./customer-api:/var/www/storage/framework/cache
    depends_on:
      - database
      - searcher
    networks:
      - mynetwork
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    image: node:18
    container_name: frontend
    working_dir: /app
    volumes:
      - ./customer-frontend:/app
    networks:
      - mynetwork
    ports:
      - "5173:5173" # Change this if needed (default Vite port)
    depends_on:
      - api
    command: >
      sh -c "npm install && npm run dev -- --host"

  database:
    image: mysql:8.0
    container_name: customer_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  searcher:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./customer-api/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./customer-api:/var/www
    depends_on:
      - api
    networks:
      - mynetwork

networks:
  mynetwork:


volumes:
  db_data:
