services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer_api
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - database
      - searcher
    networks:
      - mynetwork

  database:
    image: mysql:8.0
    container_name: customer_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  searcher:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - api
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
